version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_service
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app

  frontend:
    build: ./frontend
    container_name: frontend_service
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

